import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/common/sidebar";
import { links, Navbar } from "@/components/common/navbar";
import Providers from "@/components/common/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Review CV",
  description: "Generated by Reem ebrahim",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
      
           <Providers>
          {/* <PropertiesProvider> */}
          <div className="flex relative min-h-screen bg-white w-full">
            <Sidebar links={links} />

            <div className="flex flex-col flex-1  bg-black  h-auto ">
              
              <Navbar />
              {children}
            </div>
          </div>
          {/* </PropertiesProvider> */}
        </Providers>
      </body>
    </html>
  );
}
